name: Koa2 Server Docker Image Build

# https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.13.2]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # # 指定nodejs版本
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"

      # # 安装依赖
      # - name: install
      #   run: npm install

      # 制作docker镜像并推送到dockerhub
      - name: build and push docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          # docker image build -t koa:latest .
          docker-compose build
          docker tag koa:latest srect/koa:latest
          docker push srect/koa:latest
          docker logout
